# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-28 15:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_bloguser_blogusersposts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloguser',
            name='blogusersposts',
        ),
    ]
