# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-28 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_auto_20171223_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='blogusersposts',
            field=models.ManyToManyField(blank=True, null=True, to='test_app.BlogPost'),
        ),
    ]
