# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-28 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_remove_bloguser_blogusersposts'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='subscribers',
            field=models.ManyToManyField(blank=True, null=True, related_name='_bloguser_subscribers_+', to='test_app.BlogUser', verbose_name='\u041f\u043e\u0434\u043f\u0438\u0441\u0447\u0438\u043a\u0438'),
        ),
    ]
